; HEADER_BLOCK_START
; generated by OrcaSlicer 1.6.6 on 2023-09-09 at 08:58:44
; total layer number: 1
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START
; thumbnail begin 300x300 2952
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAIbElEQVR4Ae3dzY9VZx3A8bNo+oKlDG
; aADIjeUtqhOFVEmFonJrcaNJhG0JDYpomZSAzG2BTfunADC12wkaRuulES49ZU1y5w7aKYuNGkCSvd
; dMGfQPujnfQW5sK997w9z3k+n+S7a8KCmdNzfn1+T6sKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEjRrkceWjq465FR
; BZCyjYO7xu++/vyt6OW1vZsVQIp+8/Unr773xsbtyX7/7aevxRtXBZCCtb2fOvbOhRM3735YbXV989
; iN009/+mwF0KcLJ/ZfnPagmiw+EeOf9bYFdC4ePPHmNMvDarK/vrx23UAe6EwM0+d9UG33tlUBtCmG
; 6HUeVne/bflEBBr3oMF6nbctA3mgMb/aOHip6QfV3cWRCG9bwMLirWqRwfqixZ8Vf2YFMI9Zjyu08Y
; loIA/MJD7L/vTdZ9/u42E1meMPwH1t7QH2/bCafNuyjwjcY7s9wFSyjwjc0dZxhaaLgXy8AVZAmfoa
; rNf5RLSPCIWJX/gYauf0sJrMQB4KUXcPMLW3rQoYpib3AFN62/KJCAOSy2C9ztuWfUQYgC72AFN5aN
; lHhEx1vQeYSvYRITO5HVdo423LQB4SF59DQxysL5rjD5CooQ/WF81AHhKT8h5gKhnIQ89KHawvmoE8
; 9KT0wfqi2UeEDqVywV7uGchDy2J4nNIFe7nngkBoicF6e7kgEBriuEI3xUDe8QeooZQ9wFQykIcFxD
; DYcYX+MpCHGQ3lgr3cs48ID2APML1cEAh3MVhPO/uI8BHHFfLJPiLFsgeYZ/YRKY49wLxz/IEi2AMc
; Vo4/MFjxv1m3Bzi87CMyOAbrw88+ItlzXKGs7COSLYP1MjOQp8pJ/KDGMDanXzI1n4E8ybMHqMnsI5
; Ise4Caln1EkmGwrlmyj0jvXLCnebOPSOfsAapO9hHpjOMKaiIDeVplD1Bt5PgDjYvXd3uAaisDeRpj
; D1BdZSDPwgzW1UcG8szNYF19Zh+RmdgDVEoZyDOVPUClmAsCuYc9QKWeCwKxB6isckFgwewBKscM5A
; vjuIKGUAzkHX8YOMcVNKTsIw5UvD4brGuouSBwQAzWVUL2EQfAHqBKyz5ihgzWVXL2ETNisC45/pA8
; F+xJ92YfMUEbB3eNXbAnbZ99xIQYrEuzZR+xR44rSPNnH7EHBuvS4hnId8QFe1JzGci3yAV7UvPZR2
; yBPUCp3ewjNsBgXeou+4g1uGBP6if7iHOwByj1n33EGTiuIKWTgfwU9gCldHP8YYI9QCn97CNW9gCl
; 3CpyH9FxBSnfYiAfX0ZVCX74pRWDdSnzihnIj0dLZ//9k5NmVlLG/fe19dvffGr3ZlWCp3Y/duytl5
; 7xXwWlDPvjmSPX9+98uLwzWq+s7b34n5+ue9uSMuh/v3jh9vnjK5eqksXb1j82j93M6S9OKq1//ujL
; t44s7xhXfOjyeHTt/7/8alZ/iVIJXX5xdK3iXnHcwUBeSqMYrJ/cv3NcMd3K4w+Pfvetw962pB6Lwf
; ruxx4aVczmzOrypoG81G0xWD93dI+F50XEQP4PZ1Ydf5A66M/fe7bM4wpN+9kLn7nqE1Fqr59/8DtW
; 0ZzV5R2OP0gN968fn7j1hX2PjyuaF1viV04dMpCXGuitl565XtG+U4d220eUFqyoPcBU2EeU5q/YPc
; BUvLZ+4KrjD9L9i+MKBuuJsI8oTc9gPVG//caTBvLSRG+ePmywnrL1A0+MDeRVevYAMxKfiPYRVWr2
; ADPlgkCVVAzWX31unz3AnMXb1t9/8MWbOf3gSfMWF+yNlh51XGEo3tj4rH1EDTIX7A1UXBAY/ybK6Y
; dRmlYM1h1XGLjYRzSQV+7ZAyxM7CMayCu3YrD+ndVlg/US2UdUTrlgjztiH9EnolLOHiCfYB9RKWYP
; kPuyj6hUMlhnJuPRkgsC1Vsu2GNuW/uIOf2gK//sAVKLfUR1URxXOH985VIFddlHVJvF9sWR5R3jCp
; pkH1FNZw+QVsU+4jsXTvhEVK3sAdIZ+4iqk8E6vbCPqHmKwfq5o3vsAdIf+4iaJXuAJMU+oqZlD5Ak
; 2UfUZPYAyYJ9RNkDJCv2EcvMHiDZMpAvqziuYLBO9mIg7/jDcIvjCgbrDIqB/DAzWGfQDOSH05VTh9
; 6uYOjWDzwxNpDPtxisn9y/c1xBKbYuCPS2lVf2ACmaCwLzKAbrrz63zx4guCAw7eLvZrT0qOMKMMkF
; gen16699zgV7ME1cEBhX5ub0Sz3EHFeAGbkgsN/sAcICXBDYbTcvfsUeINRhH7GbXLAHDYp9xHdff9
; 7bVsPZA4SW2EdsNoN16IB9xPq9efqwwTp0xT7iYtkDhJ7YR5wve4CQAPuI9y8G6+ePr1yqgDTYR9y+
; 2Bo4srxjXAHpsY/4cZdfHNkDhNSVvo8Yg3XHFSAjpe4jGqxDxkrZR4zB+rmje1ywB7kb+j6iPUAYoN
; hHHNonoj1AGLCh7CPaA4SC5LyP6II9KNB4tHQ2p33EOK7ggj0oWC4D+TiuYLAO3JHqPqI9QGBbqQ3k
; 7QECD5TCQN4eIDCzvi4IdMEesJCuLwi0BwjUdmZ1ebPNgbw9QKBR8bb1t1fWbjT9sPrL9z9/w3EFoB
; VNXhBoDxBoXVwQWOf4gz1AoFNxQeCVU4fmHsjbAwR6ExcEznL8wR4gkIQH7SPaAwSSExcETh5/iOMK
; ButAsrb2EQ3WAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAut4HUTV3E+QPZlcAAAAASUVORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.42mm
; top infill extrusion width = 0.42mm
; support material extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=首层测试.STL_id_0_copy_0 CENTER=75,75 POLYGON=[[25,25],[125,25],[125,125],[25,125],[25,25]]
M73 P0 R5
;TYPE:Custom
BED_MESH_PROFILE LOAD='default'

G28 ; home all axes
 
G92 E0 ; reset extruder
 
G1 Z1.0 F3000 ; move z up little to prevent scratching of surface

M190 S60 ; wait for bed temp

Z_TILT_ADJUST

G28 ; home all axes

M109 S200 ; wait for extruder temp
 
G1 X10 Y20 Z0.3 F5000.0 ; move to start-line position
 
G1 X10 Y130.0 Z0.2 F1500.0 E10 ; draw 1st line
 
G1 X10 Y130.0 Z0.3 F5000.0 ; move to side a little
 
G1 X10 Y20 Z0.3 F1500.0 E20 ; draw 2nd line
 
G92 E0 ; reset extruder
 
M73 P1 R4
G1 Z1.0 F3000 ; move z up little to prevent scratching of surface
G90
G21
M83 ; use relative distances for extrusion
; filament start gcode
M106 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2
G92 E0

G1 E-1 F4800
;AFTER_LAYER_CHANGE
;0.2
SET_VELOCITY_LIMIT ACCEL=500 ACCEL_TO_DECEL=250
; printing object 首层测试.STL id:0 copy 0
EXCLUDE_OBJECT_START NAME=首层测试.STL_id_0_copy_0
M73 P3 R4
G1 X123.636 Y123.636 F21000
G1 Z.2
G1 E1 F4800
;TYPE:Inner wall
;WIDTH:0.5
G1 F3000
G1 X26.364 Y123.636 E3.51209
G1 X26.364 Y26.364 E3.51209
G1 X123.636 Y26.364 E3.51209
M73 P4 R4
G1 X123.636 Y123.596 E3.51065
G1 X124.093 Y124.093 F21000
M73 P5 R4
G1 F3000
M73 P6 R4
G1 X25.907 Y124.093 E3.5451
G1 X25.907 Y25.907 E3.5451
G1 X124.093 Y25.907 E3.5451
G1 X124.093 Y124.053 E3.54365
M73 P7 R4
G1 X124.55 Y124.55 F21000
;TYPE:Outer wall
M73 P8 R4
G1 F3000
G1 X25.45 Y124.55 E3.57811
G1 X25.45 Y25.45 E3.57811
G1 X124.55 Y25.45 E3.57811
M73 P9 R4
G1 X124.55 Y124.51 E3.57666
M73 P10 R4
G1 E-.7 F4800
;WIPE_START
G1 F3000
M73 P11 R4
G1 X123.55 Y124.51 E-.285
;WIPE_END
G1 E-.015 F4800
G1 X122.526 Y26.547 F21000
G1 E1 F4800
;TYPE:Bottom surface
;WIDTH:0.501483
G1 F6000
G1 X123.247 Y27.268 E.03696
G1 X123.247 Y27.917 E.02349
G1 X122.083 Y26.753 E.05964
G1 X121.435 Y26.753 E.02349
G1 X123.247 Y28.565 E.09286
G1 X123.247 Y29.214 E.02349
G1 X120.786 Y26.753 E.12608
M73 P12 R4
G1 X120.138 Y26.753 E.02349
G1 X123.247 Y29.862 E.15931
G1 X123.247 Y30.511 E.02349
G1 X119.489 Y26.753 E.19253
G1 X118.841 Y26.753 E.02349
G1 X123.247 Y31.159 E.22575
G1 X123.247 Y31.808 E.02349
G1 X118.192 Y26.753 E.25897
G1 X117.544 Y26.753 E.02349
G1 X123.247 Y32.456 E.29219
G1 X123.247 Y33.105 E.02349
G1 X116.895 Y26.753 E.32541
G1 X116.247 Y26.753 E.02349
G1 X123.247 Y33.753 E.35863
G1 X123.247 Y34.402 E.02349
G1 X115.598 Y26.753 E.39185
G1 X114.95 Y26.753 E.02349
G1 X123.247 Y35.05 E.42508
G1 X123.247 Y35.699 E.02349
G1 X114.301 Y26.753 E.4583
G1 X113.653 Y26.753 E.02349
G1 X123.247 Y36.347 E.49152
G1 X123.247 Y36.996 E.02349
G1 X113.004 Y26.753 E.52474
M73 P13 R4
G1 X112.355 Y26.753 E.02349
G1 X123.247 Y37.645 E.55796
G1 X123.247 Y38.293 E.02349
G1 X111.707 Y26.753 E.59118
G1 X111.058 Y26.753 E.02349
G1 X123.247 Y38.942 E.6244
G1 X123.247 Y39.59 E.02349
G1 X110.41 Y26.753 E.65762
G1 X109.761 Y26.753 E.02349
G1 X123.247 Y40.239 E.69084
G1 X123.247 Y40.887 E.02349
G1 X109.113 Y26.753 E.72407
G1 X108.464 Y26.753 E.02349
G1 X123.247 Y41.536 E.75729
G1 X123.247 Y42.184 E.02349
G1 X107.816 Y26.753 E.79051
M73 P14 R4
G1 X107.167 Y26.753 E.02349
G1 X123.247 Y42.833 E.82373
G1 X123.247 Y43.481 E.02349
G1 X106.519 Y26.753 E.85695
G1 X105.87 Y26.753 E.02349
G1 X123.247 Y44.13 E.89017
G1 X123.247 Y44.778 E.02349
G1 X105.222 Y26.753 E.92339
G1 X104.573 Y26.753 E.02349
G1 X123.247 Y45.427 E.95661
G1 X123.247 Y46.075 E.02349
G1 X103.925 Y26.753 E.98984
G1 X103.276 Y26.753 E.02349
G1 X123.247 Y46.724 E1.02306
M73 P15 R4
G1 X123.247 Y47.372 E.02349
G1 X102.628 Y26.753 E1.05628
G1 X101.979 Y26.753 E.02349
G1 X123.247 Y48.021 E1.0895
G1 X123.247 Y48.669 E.02349
G1 X101.331 Y26.753 E1.12272
G1 X100.682 Y26.753 E.02349
G1 X123.247 Y49.318 E1.15594
G1 X123.247 Y49.966 E.02349
G1 X100.034 Y26.753 E1.18916
G1 X99.385 Y26.753 E.02349
G1 X123.247 Y50.615 E1.22238
M73 P16 R4
G1 X123.247 Y51.263 E.02349
G1 X98.737 Y26.753 E1.25561
G1 X98.088 Y26.753 E.02349
G1 X123.247 Y51.912 E1.28883
G1 X123.247 Y52.56 E.02349
G1 X97.44 Y26.753 E1.32205
G1 X96.791 Y26.753 E.02349
G1 X123.247 Y53.209 E1.35527
G1 X123.247 Y53.857 E.02349
G1 X96.143 Y26.753 E1.38849
M73 P17 R4
G1 X95.494 Y26.753 E.02349
G1 X123.247 Y54.506 E1.42171
G1 X123.247 Y55.154 E.02349
G1 X94.846 Y26.753 E1.45493
G1 X94.197 Y26.753 E.02349
G1 X123.247 Y55.803 E1.48815
G1 X123.247 Y56.451 E.02349
G1 X93.549 Y26.753 E1.52138
G1 X92.9 Y26.753 E.02349
G1 X123.247 Y57.1 E1.5546
M73 P18 R4
G1 X123.247 Y57.748 E.02349
G1 X92.252 Y26.753 E1.58782
G1 X91.603 Y26.753 E.02349
G1 X123.247 Y58.397 E1.62104
G1 X123.247 Y59.045 E.02349
G1 X90.955 Y26.753 E1.65426
G1 X90.306 Y26.753 E.02349
G1 X123.247 Y59.694 E1.68748
G1 X123.247 Y60.342 E.02349
G1 X89.658 Y26.753 E1.7207
M73 P19 R4
G1 X89.009 Y26.753 E.02349
G1 X123.247 Y60.991 E1.75392
G1 X123.247 Y61.639 E.02349
G1 X88.361 Y26.753 E1.78715
G1 X87.712 Y26.753 E.02349
G1 X123.247 Y62.288 E1.82037
G1 X123.247 Y62.936 E.02349
G1 X87.064 Y26.753 E1.85359
M73 P20 R4
G1 X86.415 Y26.753 E.02349
G1 X123.247 Y63.585 E1.88681
G1 X123.247 Y64.233 E.02349
G1 X85.767 Y26.753 E1.92003
G1 X85.118 Y26.753 E.02349
G1 X123.247 Y64.882 E1.95325
G1 X123.247 Y65.53 E.02349
G1 X84.47 Y26.753 E1.98647
M73 P21 R4
G1 X83.821 Y26.753 E.02349
G1 X123.247 Y66.179 E2.01969
M73 P21 R3
G1 X123.247 Y66.827 E.02349
G1 X83.173 Y26.753 E2.05292
G1 X82.524 Y26.753 E.02349
G1 X123.247 Y67.476 E2.08614
G1 X123.247 Y68.124 E.02349
G1 X81.876 Y26.753 E2.11936
M73 P22 R3
G1 X81.227 Y26.753 E.02349
G1 X123.247 Y68.773 E2.15258
G1 X123.247 Y69.421 E.02349
G1 X80.579 Y26.753 E2.1858
G1 X79.93 Y26.753 E.02349
G1 X123.247 Y70.07 E2.21902
G1 X123.247 Y70.718 E.02349
G1 X79.282 Y26.753 E2.25224
M73 P23 R3
G1 X78.633 Y26.753 E.02349
G1 X123.247 Y71.367 E2.28546
G1 X123.247 Y72.015 E.02349
G1 X77.985 Y26.753 E2.31868
G1 X77.336 Y26.753 E.02349
G1 X123.247 Y72.664 E2.35191
G1 X123.247 Y73.312 E.02349
M73 P24 R3
G1 X76.688 Y26.753 E2.38513
G1 X76.039 Y26.753 E.02349
G1 X123.247 Y73.961 E2.41835
G1 X123.247 Y74.609 E.02349
G1 X75.391 Y26.753 E2.45157
G1 X74.742 Y26.753 E.02349
G1 X123.247 Y75.258 E2.48479
M73 P25 R3
G1 X123.247 Y75.906 E.02349
G1 X74.094 Y26.753 E2.51801
G1 X73.445 Y26.753 E.02349
G1 X123.247 Y76.555 E2.55123
G1 X123.247 Y77.203 E.02349
G1 X72.797 Y26.753 E2.58445
M73 P26 R3
G1 X72.148 Y26.753 E.02349
G1 X123.247 Y77.852 E2.61768
G1 X123.247 Y78.5 E.02349
G1 X71.5 Y26.753 E2.6509
G1 X70.851 Y26.753 E.02349
G1 X123.247 Y79.149 E2.68412
G1 X123.247 Y79.797 E.02349
G1 X70.203 Y26.753 E2.71734
M73 P27 R3
G1 X69.554 Y26.753 E.02349
G1 X123.247 Y80.446 E2.75056
G1 X123.247 Y81.094 E.02349
G1 X68.906 Y26.753 E2.78378
G1 X68.257 Y26.753 E.02349
G1 X123.247 Y81.743 E2.817
M73 P28 R3
G1 X123.247 Y82.391 E.02349
G1 X67.609 Y26.753 E2.85022
G1 X66.96 Y26.753 E.02349
G1 X123.247 Y83.04 E2.88345
G1 X123.247 Y83.688 E.02349
G1 X66.312 Y26.753 E2.91667
M73 P29 R3
G1 X65.663 Y26.753 E.02349
G1 X123.247 Y84.337 E2.94989
G1 X123.247 Y84.985 E.02349
G1 X65.015 Y26.753 E2.98311
G1 X64.366 Y26.753 E.02349
G1 X123.247 Y85.634 E3.01633
M73 P30 R3
G1 X123.247 Y86.282 E.02349
G1 X63.718 Y26.753 E3.04955
G1 X63.069 Y26.753 E.02349
G1 X123.247 Y86.931 E3.08277
G1 X123.247 Y87.579 E.02349
G1 X62.421 Y26.753 E3.11599
M73 P31 R3
G1 X61.772 Y26.753 E.02349
G1 X123.247 Y88.228 E3.14922
G1 X123.247 Y88.876 E.02349
G1 X61.124 Y26.753 E3.18244
G1 X60.475 Y26.753 E.02349
G1 X123.247 Y89.525 E3.21566
M73 P32 R3
G1 X123.247 Y90.173 E.02349
G1 X59.827 Y26.753 E3.24888
G1 X59.178 Y26.753 E.02349
G1 X123.247 Y90.822 E3.2821
M73 P33 R3
G1 X123.247 Y91.471 E.02349
G1 X58.529 Y26.753 E3.31532
G1 X57.881 Y26.753 E.02349
G1 X123.247 Y92.119 E3.34854
G1 X123.247 Y92.768 E.02349
G1 X57.232 Y26.753 E3.38176
M73 P34 R3
G1 X56.584 Y26.753 E.02349
G1 X123.247 Y93.416 E3.41499
G1 X123.247 Y94.065 E.02349
G1 X55.935 Y26.753 E3.44821
G1 X55.287 Y26.753 E.02349
G1 X123.247 Y94.713 E3.48143
M73 P35 R3
G1 X123.247 Y95.362 E.02349
G1 X54.638 Y26.753 E3.51465
G1 X53.99 Y26.753 E.02349
G1 X123.247 Y96.01 E3.54787
M73 P36 R3
G1 X123.247 Y96.659 E.02349
G1 X53.341 Y26.753 E3.58109
G1 X52.693 Y26.753 E.02349
G1 X123.247 Y97.307 E3.61431
G1 X123.247 Y97.956 E.02349
G1 X52.044 Y26.753 E3.64753
M73 P37 R3
G1 X51.396 Y26.753 E.02349
G1 X123.247 Y98.604 E3.68075
G1 X123.247 Y99.253 E.02349
G1 X50.747 Y26.753 E3.71398
M73 P38 R3
G1 X50.099 Y26.753 E.02349
G1 X123.247 Y99.901 E3.7472
G1 X123.247 Y100.55 E.02349
G1 X49.45 Y26.753 E3.78042
G1 X48.802 Y26.753 E.02349
G1 X123.247 Y101.198 E3.81364
M73 P39 R3
G1 X123.247 Y101.847 E.02349
G1 X48.153 Y26.753 E3.84686
G1 X47.505 Y26.753 E.02349
G1 X123.247 Y102.495 E3.88008
M73 P40 R3
G1 X123.247 Y103.144 E.02349
G1 X46.856 Y26.753 E3.9133
G1 X46.208 Y26.753 E.02349
G1 X123.247 Y103.792 E3.94652
G1 X123.247 Y104.441 E.02349
M73 P40 R2
G1 X45.559 Y26.753 E3.97975
M73 P41 R2
G1 X44.911 Y26.753 E.02349
G1 X123.247 Y105.089 E4.01297
G1 X123.247 Y105.738 E.02349
G1 X44.262 Y26.753 E4.04619
M73 P42 R2
G1 X43.614 Y26.753 E.02349
G1 X123.247 Y106.386 E4.07941
G1 X123.247 Y107.035 E.02349
G1 X42.965 Y26.753 E4.11263
M73 P43 R2
G1 X42.317 Y26.753 E.02349
G1 X123.247 Y107.683 E4.14585
G1 X123.247 Y108.332 E.02349
G1 X41.668 Y26.753 E4.17907
M73 P44 R2
G1 X41.02 Y26.753 E.02349
G1 X123.247 Y108.98 E4.21229
G1 X123.247 Y109.629 E.02349
G1 X40.371 Y26.753 E4.24552
G1 X39.723 Y26.753 E.02349
G1 X123.247 Y110.277 E4.27874
M73 P45 R2
G1 X123.247 Y110.926 E.02349
G1 X39.074 Y26.753 E4.31196
G1 X38.426 Y26.753 E.02349
G1 X123.247 Y111.574 E4.34518
M73 P46 R2
G1 X123.247 Y112.223 E.02349
G1 X37.777 Y26.753 E4.3784
G1 X37.129 Y26.753 E.02349
G1 X123.247 Y112.871 E4.41162
M73 P47 R2
G1 X123.247 Y113.52 E.02349
G1 X36.48 Y26.753 E4.44484
G1 X35.832 Y26.753 E.02349
G1 X123.247 Y114.168 E4.47806
M73 P48 R2
G1 X123.247 Y114.817 E.02349
G1 X35.183 Y26.753 E4.51129
G1 X34.535 Y26.753 E.02349
G1 X123.247 Y115.465 E4.54451
M73 P49 R2
G1 X123.247 Y116.114 E.02349
G1 X33.886 Y26.753 E4.57773
G1 X33.238 Y26.753 E.02349
G1 X123.247 Y116.762 E4.61095
M73 P50 R2
G1 X123.247 Y117.411 E.02349
G1 X32.589 Y26.753 E4.64417
G1 X31.941 Y26.753 E.02349
G1 X123.247 Y118.059 E4.67739
M73 P51 R2
G1 X123.247 Y118.708 E.02349
G1 X31.292 Y26.753 E4.71061
G1 X30.644 Y26.753 E.02349
G1 X123.247 Y119.356 E4.74383
M73 P52 R2
G1 X123.247 Y120.005 E.02349
G1 X29.995 Y26.753 E4.77706
G1 X29.347 Y26.753 E.02349
G1 X123.247 Y120.653 E4.81028
M73 P53 R2
G1 X123.247 Y121.302 E.02349
G1 X28.698 Y26.753 E4.8435
G1 X28.05 Y26.753 E.02349
G1 X123.247 Y121.95 E4.87672
M73 P54 R2
G1 X123.247 Y122.599 E.02349
G1 X27.401 Y26.753 E4.90994
G1 X26.753 Y26.753 E.02349
G1 X123.247 Y123.247 E4.94316
M73 P55 R2
G1 X122.599 Y123.247 E.02349
G1 X26.753 Y27.401 E4.90994
G1 X26.753 Y28.05 E.02349
G1 X121.95 Y123.247 E4.87672
M73 P56 R2
G1 X121.302 Y123.247 E.02349
G1 X26.753 Y28.698 E4.8435
G1 X26.753 Y29.347 E.02349
G1 X120.653 Y123.247 E4.81028
M73 P57 R2
G1 X120.005 Y123.247 E.02349
G1 X26.753 Y29.995 E4.77706
G1 X26.753 Y30.644 E.02349
G1 X119.356 Y123.247 E4.74384
M73 P58 R2
G1 X118.708 Y123.247 E.02349
G1 X26.753 Y31.292 E4.71062
G1 X26.753 Y31.941 E.02349
G1 X118.059 Y123.247 E4.6774
M73 P59 R2
G1 X117.411 Y123.247 E.02349
G1 X26.753 Y32.589 E4.64417
G1 X26.753 Y33.238 E.02349
G1 X116.762 Y123.247 E4.61095
M73 P60 R2
G1 X116.114 Y123.247 E.02349
G1 X26.753 Y33.886 E4.57773
G1 X26.753 Y34.535 E.02349
G1 X115.465 Y123.247 E4.54451
M73 P61 R1
G1 X114.817 Y123.247 E.02349
G1 X26.753 Y35.183 E4.51129
G1 X26.753 Y35.832 E.02349
G1 X114.168 Y123.247 E4.47807
M73 P62 R1
G1 X113.52 Y123.247 E.02349
G1 X26.753 Y36.48 E4.44485
G1 X26.753 Y37.129 E.02349
G1 X112.871 Y123.247 E4.41163
M73 P63 R1
G1 X112.223 Y123.247 E.02349
G1 X26.753 Y37.777 E4.3784
G1 X26.753 Y38.426 E.02349
G1 X111.574 Y123.247 E4.34518
G1 X110.926 Y123.247 E.02349
M73 P64 R1
G1 X26.753 Y39.074 E4.31196
G1 X26.753 Y39.723 E.02349
G1 X110.277 Y123.247 E4.27874
G1 X109.629 Y123.247 E.02349
G1 X26.753 Y40.371 E4.24552
M73 P65 R1
G1 X26.753 Y41.02 E.02349
G1 X108.98 Y123.247 E4.2123
G1 X108.332 Y123.247 E.02349
G1 X26.753 Y41.668 E4.17908
M73 P66 R1
G1 X26.753 Y42.317 E.02349
G1 X107.683 Y123.247 E4.14586
G1 X107.035 Y123.247 E.02349
G1 X26.753 Y42.965 E4.11263
M73 P67 R1
G1 X26.753 Y43.614 E.02349
G1 X106.386 Y123.247 E4.07941
G1 X105.738 Y123.247 E.02349
G1 X26.753 Y44.262 E4.04619
M73 P68 R1
G1 X26.753 Y44.911 E.02349
G1 X105.089 Y123.247 E4.01297
G1 X104.441 Y123.247 E.02349
G1 X26.753 Y45.559 E3.97975
G1 X26.753 Y46.208 E.02349
G1 X103.792 Y123.247 E3.94653
M73 P69 R1
G1 X103.144 Y123.247 E.02349
G1 X26.753 Y46.856 E3.91331
G1 X26.753 Y47.505 E.02349
G1 X102.495 Y123.247 E3.88009
M73 P70 R1
G1 X101.847 Y123.247 E.02349
G1 X26.753 Y48.153 E3.84686
G1 X26.753 Y48.802 E.02349
G1 X101.198 Y123.247 E3.81364
M73 P71 R1
G1 X100.55 Y123.247 E.02349
G1 X26.753 Y49.45 E3.78042
G1 X26.753 Y50.099 E.02349
G1 X99.901 Y123.247 E3.7472
G1 X99.253 Y123.247 E.02349
G1 X26.753 Y50.747 E3.71398
M73 P72 R1
G1 X26.753 Y51.396 E.02349
G1 X98.604 Y123.247 E3.68076
G1 X97.956 Y123.247 E.02349
G1 X26.753 Y52.044 E3.64754
M73 P73 R1
G1 X26.753 Y52.693 E.02349
G1 X97.307 Y123.247 E3.61432
G1 X96.659 Y123.247 E.02349
G1 X26.753 Y53.341 E3.58109
G1 X26.753 Y53.99 E.02349
G1 X96.01 Y123.247 E3.54787
M73 P74 R1
G1 X95.362 Y123.247 E.02349
G1 X26.753 Y54.638 E3.51465
G1 X26.753 Y55.287 E.02349
G1 X94.713 Y123.247 E3.48143
M73 P75 R1
G1 X94.065 Y123.247 E.02349
G1 X26.753 Y55.935 E3.44821
G1 X26.753 Y56.584 E.02349
G1 X93.416 Y123.247 E3.41499
G1 X92.768 Y123.247 E.02349
G1 X26.753 Y57.232 E3.38177
M73 P76 R1
G1 X26.753 Y57.881 E.02349
G1 X92.119 Y123.247 E3.34855
G1 X91.471 Y123.247 E.02349
G1 X26.753 Y58.529 E3.31533
G1 X26.753 Y59.178 E.02349
G1 X90.822 Y123.247 E3.2821
M73 P77 R1
G1 X90.174 Y123.247 E.02349
G1 X26.753 Y59.826 E3.24888
G1 X26.753 Y60.475 E.02349
G1 X89.525 Y123.247 E3.21566
M73 P78 R1
G1 X88.877 Y123.247 E.02349
G1 X26.753 Y61.123 E3.18244
G1 X26.753 Y61.772 E.02349
G1 X88.228 Y123.247 E3.14922
G1 X87.58 Y123.247 E.02349
G1 X26.753 Y62.42 E3.116
M73 P79 R1
G1 X26.753 Y63.069 E.02349
G1 X86.931 Y123.247 E3.08278
G1 X86.283 Y123.247 E.02349
G1 X26.753 Y63.717 E3.04956
G1 X26.753 Y64.366 E.02349
G1 X85.634 Y123.247 E3.01633
M73 P80 R1
G1 X84.986 Y123.247 E.02349
G1 X26.753 Y65.014 E2.98311
M73 P80 R0
G1 X26.753 Y65.663 E.02349
G1 X84.337 Y123.247 E2.94989
G1 X83.689 Y123.247 E.02349
G1 X26.753 Y66.311 E2.91667
M73 P81 R0
G1 X26.753 Y66.96 E.02349
G1 X83.04 Y123.247 E2.88345
G1 X82.391 Y123.247 E.02349
G1 X26.753 Y67.609 E2.85023
G1 X26.753 Y68.257 E.02349
G1 X81.743 Y123.247 E2.81701
M73 P82 R0
G1 X81.094 Y123.247 E.02349
G1 X26.753 Y68.906 E2.78379
G1 X26.753 Y69.554 E.02349
G1 X80.446 Y123.247 E2.75056
G1 X79.797 Y123.247 E.02349
G1 X26.753 Y70.203 E2.71734
M73 P83 R0
G1 X26.753 Y70.851 E.02349
G1 X79.149 Y123.247 E2.68412
G1 X78.5 Y123.247 E.02349
G1 X26.753 Y71.5 E2.6509
G1 X26.753 Y72.148 E.02349
G1 X77.852 Y123.247 E2.61768
M73 P84 R0
G1 X77.203 Y123.247 E.02349
G1 X26.753 Y72.797 E2.58446
G1 X26.753 Y73.445 E.02349
G1 X76.555 Y123.247 E2.55124
G1 X75.906 Y123.247 E.02349
G1 X26.753 Y74.094 E2.51802
M73 P85 R0
G1 X26.753 Y74.742 E.02349
G1 X75.258 Y123.247 E2.48479
G1 X74.609 Y123.247 E.02349
G1 X26.753 Y75.391 E2.45157
G1 X26.753 Y76.039 E.02349
G1 X73.961 Y123.247 E2.41835
G1 X73.312 Y123.247 E.02349
G1 X26.753 Y76.688 E2.38513
M73 P86 R0
G1 X26.753 Y77.336 E.02349
G1 X72.664 Y123.247 E2.35191
G1 X72.015 Y123.247 E.02349
G1 X26.753 Y77.985 E2.31869
G1 X26.753 Y78.633 E.02349
G1 X71.367 Y123.247 E2.28547
M73 P87 R0
G1 X70.718 Y123.247 E.02349
G1 X26.753 Y79.282 E2.25225
G1 X26.753 Y79.93 E.02349
G1 X70.07 Y123.247 E2.21902
G1 X69.421 Y123.247 E.02349
G1 X26.753 Y80.579 E2.1858
G1 X26.753 Y81.227 E.02349
G1 X68.773 Y123.247 E2.15258
M73 P88 R0
G1 X68.124 Y123.247 E.02349
G1 X26.753 Y81.876 E2.11936
G1 X26.753 Y82.524 E.02349
G1 X67.476 Y123.247 E2.08614
G1 X66.827 Y123.247 E.02349
G1 X26.753 Y83.173 E2.05292
G1 X26.753 Y83.821 E.02349
G1 X66.179 Y123.247 E2.0197
M73 P89 R0
G1 X65.53 Y123.247 E.02349
G1 X26.753 Y84.47 E1.98648
G1 X26.753 Y85.118 E.02349
G1 X64.882 Y123.247 E1.95325
G1 X64.233 Y123.247 E.02349
G1 X26.753 Y85.767 E1.92003
G1 X26.753 Y86.415 E.02349
G1 X63.585 Y123.247 E1.88681
M73 P90 R0
G1 X62.936 Y123.247 E.02349
G1 X26.753 Y87.064 E1.85359
G1 X26.753 Y87.712 E.02349
G1 X62.288 Y123.247 E1.82037
G1 X61.639 Y123.247 E.02349
G1 X26.753 Y88.361 E1.78715
G1 X26.753 Y89.009 E.02349
G1 X60.991 Y123.247 E1.75393
M73 P91 R0
G1 X60.342 Y123.247 E.02349
G1 X26.753 Y89.658 E1.72071
G1 X26.753 Y90.306 E.02349
G1 X59.694 Y123.247 E1.68749
G1 X59.045 Y123.247 E.02349
G1 X26.753 Y90.955 E1.65426
G1 X26.753 Y91.603 E.02349
G1 X58.397 Y123.247 E1.62104
M73 P92 R0
G1 X57.748 Y123.247 E.02349
G1 X26.753 Y92.252 E1.58782
G1 X26.753 Y92.9 E.02349
G1 X57.1 Y123.247 E1.5546
G1 X56.451 Y123.247 E.02349
G1 X26.753 Y93.549 E1.52138
G1 X26.753 Y94.197 E.02349
G1 X55.803 Y123.247 E1.48816
G1 X55.154 Y123.247 E.02349
G1 X26.753 Y94.846 E1.45494
M73 P93 R0
G1 X26.753 Y95.494 E.02349
G1 X54.506 Y123.247 E1.42172
G1 X53.857 Y123.247 E.02349
G1 X26.753 Y96.143 E1.38849
G1 X26.753 Y96.791 E.02349
G1 X53.209 Y123.247 E1.35527
G1 X52.56 Y123.247 E.02349
G1 X26.753 Y97.44 E1.32205
G1 X26.753 Y98.088 E.02349
G1 X51.912 Y123.247 E1.28883
M73 P94 R0
G1 X51.263 Y123.247 E.02349
G1 X26.753 Y98.737 E1.25561
G1 X26.753 Y99.385 E.02349
G1 X50.615 Y123.247 E1.22239
G1 X49.966 Y123.247 E.02349
G1 X26.753 Y100.034 E1.18917
G1 X26.753 Y100.682 E.02349
G1 X49.318 Y123.247 E1.15595
G1 X48.669 Y123.247 E.02349
G1 X26.753 Y101.331 E1.12272
G1 X26.753 Y101.979 E.02349
G1 X48.021 Y123.247 E1.0895
M73 P95 R0
G1 X47.372 Y123.247 E.02349
G1 X26.753 Y102.628 E1.05628
G1 X26.753 Y103.276 E.02349
G1 X46.724 Y123.247 E1.02306
G1 X46.075 Y123.247 E.02349
G1 X26.753 Y103.925 E.98984
G1 X26.753 Y104.573 E.02349
G1 X45.427 Y123.247 E.95662
G1 X44.778 Y123.247 E.02349
G1 X26.753 Y105.222 E.9234
G1 X26.753 Y105.87 E.02349
G1 X44.13 Y123.247 E.89018
M73 P96 R0
G1 X43.481 Y123.247 E.02349
G1 X26.753 Y106.519 E.85695
G1 X26.753 Y107.167 E.02349
G1 X42.833 Y123.247 E.82373
G1 X42.184 Y123.247 E.02349
G1 X26.753 Y107.816 E.79051
G1 X26.753 Y108.464 E.02349
G1 X41.536 Y123.247 E.75729
G1 X40.887 Y123.247 E.02349
G1 X26.753 Y109.113 E.72407
G1 X26.753 Y109.761 E.02349
G1 X40.239 Y123.247 E.69085
G1 X39.59 Y123.247 E.02349
G1 X26.753 Y110.41 E.65763
M73 P97 R0
G1 X26.753 Y111.058 E.02349
G1 X38.942 Y123.247 E.62441
G1 X38.293 Y123.247 E.02349
G1 X26.753 Y111.707 E.59118
G1 X26.753 Y112.355 E.02349
G1 X37.645 Y123.247 E.55796
G1 X36.996 Y123.247 E.02349
G1 X26.753 Y113.004 E.52474
G1 X26.753 Y113.652 E.02349
G1 X36.348 Y123.247 E.49152
G1 X35.699 Y123.247 E.02349
G1 X26.753 Y114.301 E.4583
G1 X26.753 Y114.949 E.02349
G1 X35.051 Y123.247 E.42508
G1 X34.402 Y123.247 E.02349
G1 X26.753 Y115.598 E.39186
M73 P98 R0
G1 X26.753 Y116.246 E.02349
G1 X33.754 Y123.247 E.35864
G1 X33.105 Y123.247 E.02349
G1 X26.753 Y116.895 E.32542
G1 X26.753 Y117.543 E.02349
G1 X32.457 Y123.247 E.29219
G1 X31.808 Y123.247 E.02349
G1 X26.753 Y118.192 E.25897
G1 X26.753 Y118.84 E.02349
G1 X31.16 Y123.247 E.22575
G1 X30.511 Y123.247 E.02349
G1 X26.753 Y119.489 E.19253
G1 X26.753 Y120.137 E.02349
G1 X29.863 Y123.247 E.15931
G1 X29.214 Y123.247 E.02349
G1 X26.753 Y120.786 E.12609
G1 X26.753 Y121.435 E.02349
G1 X28.565 Y123.247 E.09287
G1 X27.917 Y123.247 E.02349
G1 X26.753 Y122.083 E.05965
G1 X26.753 Y122.732 E.02349
G1 X27.474 Y123.453 E.03696
; stop printing object 首层测试.STL id:0 copy 0
G1 E-.7 F4800
;WIPE_START
G1 F6000
G1 X26.767 Y122.746 E-.285
;WIPE_END
G1 E-.015 F4800
EXCLUDE_OBJECT_END NAME=首层测试.STL_id_0_copy_0
M106 S0
;TYPE:Custom
; filament end gcode 
G1 E-0.5 F1000 ; retract
G92 E0.0
G1 Z30.2 E-3.0 F720 ; move print head up & retract filament
G4 ; wait
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 X0 Y105 F3000 ; park print head
M84 ; disable motors
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 784.04
; filament used [cm3] = 1.89
; filament used [g] = 2.34
; filament cost = 0.12; total filament used [g] = 2.34
; total filament cost = 0.12
; total layers count = 1
; estimated printing time (normal mode) = 5m 4s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; additional_cooling_fan_speed = 50
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_temperature_difference = 10
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; bottom_shell_layers = 3
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 0.95
; bridge_no_support = 0
; bridge_speed = 100
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0
; brim_type = no_brim
; brim_width = 5
; chamber_temperature = 0
; change_filament_gcode = 
; close_fan_the_first_x_layers = 1
; cool_plate_temp = 60
; cool_plate_temp_initial_layer = 60
; curr_bed_type = High Temp Plate
; default_acceleration = 12000
; default_filament_colour = ""
; default_filament_profile = "My Generic ABS"
; default_jerk = 0
; default_print_profile = 0.20mm Standard @MyKlipper
; deretraction_speed = 80
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = bridge_speed;brim_object_gap;brim_type;default_acceleration;elefant_foot_compensation;enable_support;gap_infill_speed;infill_wall_overlap;initial_layer_infill_speed;inner_wall_acceleration;inner_wall_speed;internal_solid_infill_line_width;internal_solid_infill_speed;outer_wall_acceleration;outer_wall_line_width;outer_wall_speed;overhang_2_4_speed;overhang_3_4_speed;overhang_4_4_speed;small_perimeter_speed;sparse_infill_density;sparse_infill_speed;support_angle;support_base_pattern_spacing;support_interface_bottom_layers;support_line_width;support_object_xy_distance;support_top_z_distance;support_type;top_shell_thickness;top_surface_line_width;top_surface_speed;travel_acceleration;tree_support_wall_count;wall_generator;xy_contour_compensation;xy_hole_compensation;additional_cooling_fan_speed;filament_cost;filament_flow_ratio;filament_max_volumetric_speed;nozzle_temperature;nozzle_temperature_initial_layer;slow_down_min_speed;deretraction_speed;machine_end_gcode;machine_start_gcode;print_host;printable_area;printable_height;retraction_length;retraction_speed;z_hop
; draft_shield = disabled
; elefant_foot_compensation = 0.15
; enable_arc_fitting = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 0
; enable_prime_tower = 0
; enable_support = 1
; enforce_support_layers = 0
; eng_plate_temp = 60
; eng_plate_temp_initial_layer = 60
; ensure_vertical_shell_thickness = 1
; exclude_object = 1
; extruder_clearance_height_to_lid = 140
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 65
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; fan_cooling_layer_time = 100
; fan_kickstart = 0
; fan_max_speed = 100
; fan_min_speed = 100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #FF8040
; filament_cost = 50
; filament_density = 1.24
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode \n"
; filament_flow_ratio = 0.95
; filament_ids = GFL99
; filament_is_support = 0
; filament_max_volumetric_speed = 20
; filament_minimal_purge_on_wipe_tower = 15
; filament_settings_id = PLA_TT150
; filament_shrink = 100%
; filament_soluble = 0
; filament_start_gcode = "; filament start gcode\n"
; filament_type = PLA
; filament_vendor = Generic
; filename_format = {input_filename_base}_{filament_type[0]}_{print_time}.gcode
; filter_out_gap_fill = 0
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_thickness = 0.3
; gap_infill_speed = 300
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; host_type = octoprint
; hot_plate_temp = 60
; hot_plate_temp_initial_layer = 60
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_direction = 45
; infill_jerk = 9
; infill_wall_overlap = 15%
; inherits_group = "0.20mm Standard @MyKlipper";"My Generic PLA";"MyKlipper 0.4 nozzle"
; initial_layer_acceleration = 500
; initial_layer_infill_speed = 100
; initial_layer_jerk = 9
; initial_layer_line_width = 0.5
; initial_layer_print_height = 0.2
; initial_layer_speed = 50
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 10000
; inner_wall_jerk = 9
; inner_wall_line_width = 0.45
; inner_wall_speed = 300
; interface_shells = 0
; internal_bridge_speed = 150%
; internal_bridge_support_thickness = 0
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.42
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 300
; ironing_flow = 10%
; ironing_pattern = zig-zag
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; layer_change_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; line_width = 0.4
; machine_end_gcode = G1 E-0.5 F1000 ; retract\nG92 E0.0\nG1{if max_layer_z < max_print_height} Z{z_offset+min(max_layer_z+30, max_print_height)}{endif} E-3.0 F720 ; move print head up & retract filament\nG4 ; wait\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nG1 X0 Y105 F3000 ; park print head\nM84 ; disable motors
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 20000,20000
; machine_max_acceleration_retracting = 5000,5000
; machine_max_acceleration_travel = 9000,9000
; machine_max_acceleration_x = 20000,20000
; machine_max_acceleration_y = 20000,20000
; machine_max_acceleration_z = 500,200
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 9,9
; machine_max_jerk_y = 9,9
; machine_max_jerk_z = 0.2,0.4
; machine_max_speed_e = 25,25
; machine_max_speed_x = 500,200
; machine_max_speed_y = 500,200
; machine_max_speed_z = 12,12
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = PAUSE
; machine_start_gcode = BED_MESH_PROFILE LOAD='default'\n\nG28 ; home all axes\n \nG92 E0 ; reset extruder\n \nG1 Z1.0 F3000 ; move z up little to prevent scratching of surface\n\nM190 S[first_layer_bed_temperature] ; wait for bed temp\n\nZ_TILT_ADJUST\n\nG28 ; home all axes\n\nM109 S[first_layer_temperature] ; wait for extruder temp\n \nG1 X10 Y20 Z0.3 F5000.0 ; move to start-line position\n \nG1 X10 Y130.0 Z0.2 F1500.0 E10 ; draw 1st line\n \nG1 X10 Y130.0 Z0.3 F5000.0 ; move to side a little\n \nG1 X10 Y20 Z0.3 F1500.0 E20 ; draw 2nd line\n \nG92 E0 ; reset extruder\n \nG1 Z1.0 F3000 ; move z up little to prevent scratching of surface
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; max_bridge_length = 10
; max_layer_height = 0.32
; max_travel_detour_distance = 0
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; nozzle_diameter = 0.4
; nozzle_hrc = 0
; nozzle_temperature = 200
; nozzle_temperature_initial_layer = 200
; nozzle_temperature_range_high = 230
; nozzle_temperature_range_low = 190
; nozzle_type = undefine
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; outer_wall_acceleration = 5000
; outer_wall_jerk = 9
; outer_wall_line_width = 0.42
; outer_wall_speed = 200
; overhang_1_4_speed = 0
; overhang_2_4_speed = 80
; overhang_3_4_speed = 60
; overhang_4_4_speed = 20
; overhang_fan_speed = 100
; overhang_fan_threshold = 50%
; overhang_speed_classic = 0
; post_process = 
; precise_outer_wall = 0
; pressure_advance = 0.02
; prime_tower_brim_width = 3
; prime_tower_width = 35
; prime_volume = 45
; print_compatible_printers = "MyKlipper 0.4 nozzle"
; print_flow_ratio = 1
; print_host = 192.168.0.107
; print_host_webui = 
; print_sequence = by layer
; print_settings_id = 0.20mm Standard @TT
; printable_area = 0x0,150x0,150x150,0x150
; printable_height = 170
; printer_model = Generic Klipper Printer
; printer_settings_id = TT150
; printer_technology = FFF
; printer_variant = 0.4
; printhost_apikey = 
; printhost_authorization_type = key
; printhost_cafile = 
; printhost_password = 
; printhost_port = 
; printhost_ssl_ignore_revoke = 0
; printhost_user = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; retract_before_wipe = 70%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_length = 1
; retraction_minimum_travel = 1
; retraction_speed = 80
; role_based_wipe_speed = 1
; scan_first_layer = 0
; seam_gap = 10%
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 1
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 0
; skirt_speed = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 8
; slow_down_layers = 0
; slow_down_min_speed = 60
; small_perimeter_speed = 60%
; small_perimeter_threshold = 0
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 40%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = grid
; sparse_infill_speed = 300
; spiral_mode = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; support_angle = 90
; support_base_pattern = rectilinear
; support_base_pattern_spacing = 3
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 1
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_pattern = rectilinear
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_line_width = 0.42
; support_material_interface_fan_speed = -1
; support_object_xy_distance = 2
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_top_z_distance = 0.1
; support_type = normal(manual)
; temperature_vitrification = 60
; template_custom_gcode = 
; textured_plate_temp = 60
; textured_plate_temp_initial_layer = 60
; thick_bridges = 0
; thumbnails = 300x300
; timelapse_type = 0
; top_shell_layers = 4
; top_shell_thickness = 0.6
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 3000
; top_surface_jerk = 9
; top_surface_line_width = 0.42
; top_surface_pattern = monotonic
; top_surface_speed = 200
; travel_acceleration = 12000
; travel_jerk = 12
; travel_speed = 350
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_diameter = 5
; tree_support_branch_distance = 5
; tree_support_brim_width = 3
; tree_support_wall_count = 2
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = classic
; wall_infill_order = inner wall/outer wall/infill
; wall_loops = 3
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 155.000
; wipe_tower_y = 220.000
; xy_contour_compensation = -0.05
; xy_hole_compensation = 0.05
; z_hop = 0
; z_hop_types = Normal Lift
; first_layer_bed_temperature = 60
; bed_shape = 0x0,150x0,150x150,0x150
; first_layer_temperature = 200
; first_layer_height = 0.200
; CONFIG_BLOCK_END


